### ISSUE TITLE
User Interface Mockup and Storyboard

### ISSUE THREAD

**Issue by afontaine** [IPPETAD/adventure.datetime#5]
Diagram the layout of your main user interface and major dialogs, with comments describing the important elements. Also, provide one storyboard sequence for a non-trivial but coherent scenario of using your application, with transitions between different states of the user interface, caused by the user manipulating the controls or providing input. Enter this information in your team wiki.

**Comment by Jtfinlay** [comment]
I can sketch out some ideas for this later today if someone wants to brainstorm. I have a few ideas and will dig through specifications.

**Comment by jesseDtucker** [comment]
I'm in

**Comment by jesseDtucker** [comment]
Update: James and I hashed out the UI pretty well on Friday. If I get some time tomorrow I'll start mocking up the UI in an android application. James: can you upload some pictures of what we worked out?

**Comment by Jtfinlay** [comment]
I uploaded some stuff 2 days ago. It's on the wiki. I'll do the dev UI stuff when I have the time, user screens are up.

**Comment by jesseDtucker** [comment]
Awesome thanks.

**Comment by jviau** [comment]
I like it overall, but:
- I hope we are designing our own logo eventually. Can't just use the Adventure Time logo, regardless of how relevant it is.
- "Browse" is a bit ambiguous for being the way to start a new story. Need to add subtext to the button or change it to "Start"
- The Mass Effect style dialog choice obscures the text. User probably wants a way to read at least part of the story and the decisions at the same time. I would suggest something more along the lines of android PIE style along the bottom.

**Comment by Jtfinlay** [comment]
PIE might work better than Mass Effect.

The text and pictures are details we haven't bothered considering yet. Right now everything presented is for general layout for each activity, so it's just full of placeholders. Obviously we won't use Adventure Time logo or Grumpy Cat pictures everywhere.

**Comment by jviau** [comment]
More ideas.
- Continue will only resume the most recent story played.
- The "Browse" should be made more robust. I suggest these tabs: "In Progress" "Downloaded" "Online". Optional should be "My Stories" (it is covered in "Develop", so not sure if it has a place here).
- Might need search ability in the browse activity.
  -"Develop" should be named "Create"
- Where are we handling account creation?

Another option is to put "Online" as a menu option named "Get More Stories!" (exclamation is key). And then micro transaction them like crazy. It's not a proper mobile app without micro transactions.

EDIT:
Forgot this last point. Since stories are allowed to have videos and photos in them (I think). When you view a story before you download it, or before you play it, there should be a graphic showing the proportional amount of text, video, and images. This way the user knows if they are getting into a primarily text based, video based, or image based story.

**Comment by afontaine** [comment]
I'm willing to sign off on this being complete. The wiki page looks extremely thorough. @CMPUT301F13T03/owners thoughts?

**Comment by Jtfinlay** [comment]
The layout for the choice dialog will need to be updated, but other than that I think everything is covered for a mock-up.

We can always revise as needed.

**Comment by afontaine** [comment]
Cool. I'm closing this for now then.
