### ISSUE TITLE
Server controller

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/adventure.datetime#79]
This is needed for integrating the server with the rest of the application. 

It could be implemented similarly to the IStoryListListener, but it would be preferably set up as its own interface - in the event that the server is slow as shit. Maybe IServerStoryListListener, or something with a name that isn't complete rubbish.

Also, I believe @jesseDtucker mentioned he did some sort of story caching, which will be important if we just want to get the story from the server once. This can be discussed.

**Comment by jesseDtucker** [comment]
Caching is handled in StoryManager (so we don't hit server / local DB excessively). Its nothing fancy. Also just to clarify: We don't need a server <b>Controller</b> per say. More of a special listener for handling the online stories. The main reason for this is so that James can make a spinny thing while we wait for server response.

**Comment by Jtfinlay** [comment]
Yeah, don't need a straight out Controller, just the listener. Maybe rename IStoryListListener to ILocalStoriesListener and then make a new IOnlineStoriesListener as well? That way we get rid of that terrible naming convention.

The caching that Jesse described works fine for me. 

This is assignment to Evan so that Jesse can get his Overview done.

**Comment by edegraff** [comment]
Done!
